# To start both apache and the resizer in a docker container

[supervisord]
nodaemon=true

[program:autoresize]
command=/bin/bash /var/www/html/autoresize.sh
priority=100
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
user = ResizeUser
environment=DIRECTORY="/var/www/html/displaycontent/plakate",RESOLUTION="746x"

[program:webserver]
# --- Replace this with your actual container service ---
command=apache2-foreground
priority=200
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
